#include "api.h"

// DO NOT EDIT THIS FILE

// Call this function appropriately
void mm_logger(struct mm_stats *stats, int virt_page, int fault_type,
               int evicted_page, int write_back, uint64_t phy_addr) {
    uint64_t idx = stats->counter;

    stats->log[idx].virt_page = virt_page;
    stats->log[idx].fault_type = fault_type;
    stats->log[idx].evicted_page = evicted_page;
    stats->log[idx].write_back = write_back;
    stats->log[idx].phy_addr = phy_addr;

    (stats->counter)++;
}
